// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfHHhf6eiiWI8WhjxnnqOWifqmnTdw5Vs',
    appId: '1:611793272527:web:a933b89a9dc4e72fb5c1ba',
    messagingSenderId: '611793272527',
    projectId: 'unikomb1',
    authDomain: 'unikomb1.firebaseapp.com',
    storageBucket: 'unikomb1.appspot.com',
    measurementId: 'G-622QSF3ZV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk1mg55IJBjdj5X7CMBB2QCyEAJg2ft3s',
    appId: '1:611793272527:android:4a3936b5db0b0978b5c1ba',
    messagingSenderId: '611793272527',
    projectId: 'unikomb1',
    storageBucket: 'unikomb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuq56N2n9FRMwl-eYennx0PvLIl5AyD1A',
    appId: '1:611793272527:ios:6f3df30a3c58074cb5c1ba',
    messagingSenderId: '611793272527',
    projectId: 'unikomb1',
    storageBucket: 'unikomb1.appspot.com',
    iosClientId: '611793272527-4jen7632gak91ua84k1jdebsu8l8r5oh.apps.googleusercontent.com',
    iosBundleId: 'com.example.unikomb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuq56N2n9FRMwl-eYennx0PvLIl5AyD1A',
    appId: '1:611793272527:ios:6f3df30a3c58074cb5c1ba',
    messagingSenderId: '611793272527',
    projectId: 'unikomb1',
    storageBucket: 'unikomb1.appspot.com',
    iosClientId: '611793272527-4jen7632gak91ua84k1jdebsu8l8r5oh.apps.googleusercontent.com',
    iosBundleId: 'com.example.unikomb',
  );
}
